# Generated by Django 5.0.6 on 2024-06-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelos', models.CharField(max_length=255)),
                ('descripción', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_store.celular')),
            ],
        ),
        migrations.AddField(
            model_name='celular',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_store.marca'),
        ),
    ]
