# Generated by Django 5.0.6 on 2024-06-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
