# Generated by Django 5.0.6 on 2024-06-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_store', '0002_celular_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='precio',
            field=models.FloatField(),
        ),
    ]
